language: java
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: hFiV6Lovn6JK96+avxszyvIGApdwale9xtA+mO5fLomET1/sAQT868Pomn+czGmdJv+lWKy//+Vd8mRowI2SUlJnbxA0UkhaK+6dXNbNeyBsT5DwlBLftf5RbjTQ0WBzsLUho6hLBT1P1dLtJvlA6OS1pT0vL7S1cdQjgKOWhqcNmhMoGWOXcdU0rUlNsWGMLhft2B3IdZDL2zc3pSdyfy2SOn1LsL5XfJEPOpw3Hz0WwNYZo9R4aOPkgw2ujWvzJv8rRbgDRw5o+kX0w8lbjRU0oQ0P+HpeaS4Ps8ouT1Hdm3KEWUmp02K1E6Sewqgo/9u33kw4NihQfQHO0C1+2CiSGr/7WgzhWfssSAWfSSFPMaHZ/OthalCKTTkgVQiySU5KTewmFcW8MuHei5TgmZVhsvdjMructgDi3qSf1000BXrXE3MrTViZYxKJY5dJQyenXcQvUbZzFrxnGEM9jANiMY3aVpscUjBNa7p6HxBwShbOOOTLz6S1QOFpOe1e1yGc0wR7KJNAHXXe90FkJDeKFKOIjAt7I9aXiPnhZmfAd9MY+sctyz1tc1LnaOsG5cd+/2SDd85W8DvfyKMEzxhMgWUkHNk3g11hAPBwhRw3DM9BoSqC6T9Tg8lsl3N70wqzLH0SY6gjOuUyAhad4/HwG6wLyh+EBYis5BUwbeE=
  app: ccyrate